### ISSUE TITLE
prometheus scrape gets target "gzip: invalid" header with http proxy

### ISSUE THREAD

**Issue by ajssmith** [skupperproject/skupper-proxy#3]
When using tcp proxy, the prometheus target is ok and metrics are gathered correctly.
A sample proxy response is the following:
http://pastebin.test.redhat.com/830684
(note: i removed most of the body contents)

**Comment by grs** [comment]
Fixed by https://github.com/skupperproject/skupper-proxy/commit/f9701ea7bade907aa1afb1b29440d5ab5b09032c

**Comment by grs** [comment]
@ajssmith are you happy with the fix? Can we close?
